spring:
  datasource:
    url: jdbc:mysql://{db-url}:3306/{db-name}
    username: {username}
    password: {password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


